# Generated by Django 5.0.6 on 2024-06-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.TextField(blank=True, null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('branch', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank_branches',
                'managed': False,
            },
        ),
    ]
